package nvaa

import (
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"testing"

	"github.com/WhatDamon/go-nvaa-codec/internal/synth"
)

// The synthetic corpus exists because the committed animations are tiny -- the
// largest is 6 KB -- and seeking, decoding and parsing all behave differently at
// real sizes. Building it once per test binary keeps the setup cost out of every
// measurement. See internal/synth for what the files contain and why.
type corpus struct {
	blob []byte
	anim *Animation
}

var (
	videoOnce   = sync.OnceValues(func() (corpus, error) { return buildCorpus(synth.VideoCorpus) })
	longGOPOnce = sync.OnceValues(func() (corpus, error) { return buildCorpus(synth.LongGOPCorpus) })
)

func buildCorpus(load func() (synth.Corpus, error)) (corpus, error) {
	built, err := load()
	if err != nil {
		return corpus{}, err
	}
	anim, err := Parse(built.Blob)
	if err != nil {
		return corpus{}, fmt.Errorf("parsing the synthetic corpus: %w", err)
	}
	return corpus{blob: built.Blob, anim: anim}, nil
}

func corpusFrom(tb testing.TB, load func() (corpus, error)) corpus {
	tb.Helper()
	loaded, err := load()
	if err != nil {
		tb.Fatal(err)
	}
	return loaded
}

func videoCorpus(tb testing.TB) corpus   { return corpusFrom(tb, videoOnce) }
func longGOPCorpus(tb testing.TB) corpus { return corpusFrom(tb, longGOPOnce) }

// heaviestGOP is the span a seek has to replay when it rewinds as far as the
// encoder allows: the longest run of frames between one keyframe and the next.
func heaviestGOP(anim *Animation) (start, end int) {
	keyframes := anim.Keyframes()
	start, end = 0, anim.FrameCount()
	for i, k := range keyframes {
		next := anim.FrameCount()
		if i+1 < len(keyframes) {
			next = keyframes[i+1]
		}
		if next-k > end-start {
			start, end = k, next
		}
	}
	return start, end
}

// readAnim reads a file from disk, failing the benchmark rather than returning
// an error: a benchmark whose subject is missing has nothing to report.
func readAnim(tb testing.TB, path string) *Animation {
	tb.Helper()

	anim, err := ReadFile(path)
	if err != nil {
		tb.Fatal(err)
	}
	return anim
}

func BenchmarkParse(b *testing.B) {
	c := videoCorpus(b)
	b.SetBytes(int64(len(c.blob)))
	b.ReportAllocs()
	b.ResetTimer()

	for range b.N {
		anim, err := Parse(c.blob)
		if err != nil {
			b.Fatal(err)
		}
		synth.Sink = anim
	}
}

func BenchmarkParseLongGOP(b *testing.B) {
	c := longGOPCorpus(b)
	b.SetBytes(int64(len(c.blob)))
	b.ReportAllocs()
	b.ResetTimer()

	for range b.N {
		anim, err := Parse(c.blob)
		if err != nil {
			b.Fatal(err)
		}
		synth.Sink = anim
	}
}

// BenchmarkParseReal measures parsing footage the synthetic corpus only imitates.
//
// The artifacts are generated by a separate project and are not committed, so a
// checkout without them skips. The parent line that appears above the per-file
// sub-benchmarks is the discovery loop, not a measurement.
func BenchmarkParseReal(b *testing.B) {
	paths := synth.Artifacts("../artifacts", "../../artifacts")
	if len(paths) == 0 {
		b.Skip("no artifacts/ directory in this checkout")
	}

	for _, path := range paths {
		b.Run(filepath.Base(path), func(b *testing.B) {
			blob, err := os.ReadFile(path)
			if err != nil {
				b.Fatal(err)
			}
			b.SetBytes(int64(len(blob)))
			b.ReportAllocs()
			b.ResetTimer()

			for range b.N {
				anim, err := Parse(blob)
				if err != nil {
					b.Fatal(err)
				}
				synth.Sink = anim
			}
		})
	}
}

func BenchmarkFrameAt(b *testing.B) {
	anim := videoCorpus(b).anim
	picks := synth.Targets(anim.FrameCount(), 1024)
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; b.Loop(); i++ {
		frame, err := anim.FrameAt(picks[i%len(picks)])
		if err != nil {
			b.Fatal(err)
		}
		synth.Sink = frame
	}
}

// BenchmarkFrameAtHeaviestGOP is the inner loop of a rewind: every frame of the
// longest span a seek can be asked to replay, in order.
func BenchmarkFrameAtHeaviestGOP(b *testing.B) {
	anim := longGOPCorpus(b).anim
	start, end := heaviestGOP(anim)
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; b.Loop(); i++ {
		frame, err := anim.FrameAt(start + i%(end-start))
		if err != nil {
			b.Fatal(err)
		}
		synth.Sink = frame
	}
}

func BenchmarkFrameAtReal(b *testing.B) {
	paths := synth.Artifacts("../artifacts", "../../artifacts")
	if len(paths) == 0 {
		b.Skip("no artifacts/ directory in this checkout")
	}

	for _, path := range paths {
		b.Run(filepath.Base(path), func(b *testing.B) {
			anim := readAnim(b, path)
			picks := synth.Targets(anim.FrameCount(), 1024)
			b.ReportAllocs()
			b.ResetTimer()

			for i := 0; b.Loop(); i++ {
				frame, err := anim.FrameAt(picks[i%len(picks)])
				if err != nil {
					b.Fatal(err)
				}
				synth.Sink = frame
			}
		})
	}
}

// BenchmarkHeaders is the walk Parse already paid for: it should read no
// payload, so its cost is the per-frame bookkeeping and nothing else.
func BenchmarkHeaders(b *testing.B) {
	anim := videoCorpus(b).anim
	b.ReportAllocs()
	b.ResetTimer()

	for range b.N {
		total := 0
		for header := range anim.Headers() {
			total += header.PayloadLength
		}
		synth.SinkInt = total
	}
}

func BenchmarkFrameAtTime(b *testing.B) {
	anim := videoCorpus(b).anim
	total := anim.TotalDuration()
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; b.Loop(); i++ {
		synth.SinkInt = anim.FrameAtTime(uint64(i) % total)
	}
}

// BenchmarkKeyframes records the cost of listing the seek points, which a player
// does once per timeline and a caller might reasonably do per seek.
func BenchmarkKeyframes(b *testing.B) {
	anim := videoCorpus(b).anim
	b.ReportAllocs()
	b.ResetTimer()

	for range b.N {
		synth.SinkInts = anim.Keyframes()
	}
}

// requireRealAllocator steps aside when the race detector is on, because it
// tracks every allocation: the counts it produces describe a build nobody ships,
// and a budget is a statement about a build somebody does.
func requireRealAllocator(t *testing.T) {
	t.Helper()

	if synth.RaceEnabled {
		t.Skip("allocation counts are not meaningful under the race detector")
	}
}

// Allocation budgets. A benchmark tells you what a path costs today; a budget
// tells you when it got worse, which is the failure that otherwise goes
// unnoticed until someone profiles a terminal.
//
// Each ceiling is the baseline as measured here plus room for a different
// allocator, not a target: these describe what the code does today, so that a
// change which doubles the garbage per frame has to argue for itself. The
// measurement each one rests on is printed by the test that uses it.
//
// FrameAt allocates a cell buffer per frame and should: a frame from it belongs
// to the caller and must outlive the next call. Keyframes() rescans every frame's
// flags on each call and so rebuilds its list. Both are per-frame costs, and a
// seek pays each of them once for every frame it replays.
const (
	parseBudgetBytes    = 400 << 10
	parseBudgetAllocs   = 20
	frameAtBudgetBytes  = 160 << 10
	frameAtBudgetAllocs = 24
	keyframesBudget     = 8 << 10
	keyframesAllocs     = 3
)

func TestParseAllocationBudget(t *testing.T) {
	requireRealAllocator(t)

	c := videoCorpus(t)

	allocs, bytes := synth.Measure(5, func() {
		anim, err := Parse(c.blob)
		if err != nil {
			t.Fatal(err)
		}
		synth.Sink = anim
	})
	t.Logf("Parse: %.0f allocs/op, %.1f KB/op for %d KB of input", allocs, bytes/1024, len(c.blob)/1024)

	if allocs > parseBudgetAllocs {
		t.Errorf("Parse allocates %.0f times, over the %d budget", allocs, parseBudgetAllocs)
	}
	if bytes > parseBudgetBytes {
		t.Errorf("Parse allocates %.1f KB, over the %.1f KB budget", bytes/1024, float64(parseBudgetBytes)/1024)
	}
}

func TestFrameAtAllocationBudget(t *testing.T) {
	requireRealAllocator(t)

	anim := videoCorpus(t).anim
	count := anim.FrameCount()

	allocs, bytes := synth.Measure(50, func() {
		for i := range count / 50 {
			frame, err := anim.FrameAt(i % count)
			if err != nil {
				t.Fatal(err)
			}
			synth.Sink = frame
		}
	})
	perFrame := float64(count/50) + 1
	t.Logf("FrameAt: %.1f allocs/frame, %.1f KB/frame", allocs/perFrame, bytes/perFrame/1024)

	if got := allocs / perFrame; got > frameAtBudgetAllocs {
		t.Errorf("FrameAt allocates %.0f times per frame, over the %d budget", got, frameAtBudgetAllocs)
	}
	if got := bytes / perFrame; got > frameAtBudgetBytes {
		t.Errorf("FrameAt allocates %.1f KB per frame, over the %.1f KB budget",
			got/1024, float64(frameAtBudgetBytes)/1024)
	}
}

func TestKeyframesAllocationBudget(t *testing.T) {
	requireRealAllocator(t)

	anim := videoCorpus(t).anim

	allocs, bytes := synth.Measure(20, func() {
		synth.SinkInts = anim.Keyframes()
	})
	t.Logf("Keyframes: %.1f allocs/op, %.1f KB/op", allocs, bytes/1024)

	if allocs > keyframesAllocs {
		t.Errorf("Keyframes allocates %.0f times, over the %d budget", allocs, keyframesAllocs)
	}
	if bytes > keyframesBudget {
		t.Errorf("Keyframes allocates %.1f KB, over the %.1f KB budget",
			bytes/1024, float64(keyframesBudget)/1024)
	}
}
